##################################
#       JoinHealth plugin        #
#               by               #
#          SpaicyGaming          #
##################################

# Users = Players with the permission joinhealth.user
# Vips = Players with the permission joinhealth.vip

Join:
  WelcomeMessage: true
  SetFoodLevel:
    active: true
    UsersFoodLevel: 20
    VipsFoodLevel: 20
  SetHealth:
    active: true
    UsersHealthLevel: 20.0
    VipsHealthLevel: 20.0

Utils:
  DisableHungerLoss: true
  DisableLifeLoss: true

Messages:
  prefix: '&7[&bJoinHealth&7]'
  noPerms: '&cSorry, you don''t have enought permissions.'
  
## DO NOT TOUCH ##
ConfigVersion: 1.2
CheckForUpdates: true