main: io.github.spaicygaming.joinhealth.JoinHealth
website: https://www.spigotmc.org/resources/joinhealth.36546/

name: JoinHealth
version: 1.3
author: SpaicyGaming

commands:
    joinhealth:
        description: Base command
        aliases: jh